"use client";

import { useEffect,useState } from "react";

// AppearanceSettings centralises the visual preference controls used by all portals.
// It writes CSS variables to <html>, allowing the existing pages to inherit theme,
// typography, density, radius, and colour choices without each page managing styles.
const colors=[{name:"Amber",value:"#f59e0b"},{name:"Blue",value:"#2563eb"},{name:"Cyan",value:"#0891b2"},{name:"Emerald",value:"#059669"},{name:"Fuchsia",value:"#c026d3"},{name:"Green",value:"#16a34a"},{name:"Indigo",value:"#4f46e5"},{name:"Lime",value:"#65a30d"},{name:"Orange",value:"#ea580c"},{name:"Pink",value:"#db2777"},{name:"Purple",value:"#7c3aed"},{name:"Red",value:"#dc2626"},{name:"Rose",value:"#e11d48"},{name:"Sky",value:"#0284c7"},{name:"Teal",value:"#0d9488"},{name:"Violet",value:"#7c3aed"}];
const bases={Neutral:"#f7f8fc",Stone:"#f5f5f4",Zinc:"#f4f4f5",Slate:"#f1f5f9",Mist:"#f6f8fb"};
const styles=[{name:"Vega",copy:"Classic shadow and balanced spacing."},{name:"Nova",copy:"Reduced spacing for compact layouts."},{name:"Maia",copy:"Soft and rounded with generous spacing."},{name:"Lyra",copy:"Boxy and sharp for structured surfaces."},{name:"Mira",copy:"Dense UI tuned for data-heavy screens."}];
const fonts={Inter:"Inter, system-ui, sans-serif",Geist:"Geist, 'Geist Sans', Inter, system-ui, sans-serif",System:"system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",Roboto:"Roboto, Inter, system-ui, sans-serif"};
const headingScale={Compact:"22px",Medium:"25px",Large:"29px"};

export function AppearanceLoader({role}:{role:"coordinator"|"supervisor"|"student"}){useEffect(()=>{const saved=localStorage.getItem(`sip-appearance-${role}`);if(!saved)return;const value=JSON.parse(saved);applyAppearance({...value,mode:value.mode||"Light",color:value.color||"#4f46e5",chartColor:value.chartColor||value.color||"#4f46e5",radius:value.radius||"Default",style:value.style||"Vega",base:value.base||"Neutral",font:value.font||"Inter",heading:value.heading||"Medium"})},[role]);return null}

export function AppearanceSettings({role,compact=false}:{role:"coordinator"|"supervisor"|"student";compact?:boolean}){
  const[mode,setMode]=useState("Light");const[color,setColor]=useState("#4f46e5");const[chartColor,setChartColor]=useState("#4f46e5");const[radius,setRadius]=useState("Default");const[style,setStyle]=useState("Vega");const[base,setBase]=useState("Neutral");const[font,setFont]=useState("Inter");const[heading,setHeading]=useState("Medium");const key=`sip-appearance-${role}`;
  useEffect(()=>{const saved=localStorage.getItem(key);if(saved){const value=JSON.parse(saved);const next={...value,mode:value.mode||"Light",color:value.color||"#4f46e5",chartColor:value.chartColor||value.color||"#4f46e5",radius:value.radius||"Default",style:value.style||"Vega",base:value.base||"Neutral",font:value.font||"Inter",heading:value.heading||"Medium"};setMode(next.mode);setColor(next.color);setChartColor(next.chartColor);setRadius(next.radius);setStyle(next.style);setBase(next.base);setFont(next.font);setHeading(next.heading);applyAppearance(next)}},[key]);
  function save(patch:Partial<AppearanceValue>){const next={mode,color,chartColor,radius,style,base,font,heading,...patch};setMode(next.mode);setColor(next.color);setChartColor(next.chartColor);setRadius(next.radius);setStyle(next.style);setBase(next.base);setFont(next.font);setHeading(next.heading);applyAppearance(next);localStorage.setItem(key,JSON.stringify(next))}
  function reset(){save({mode:"Light",color:"#4f46e5",chartColor:"#4f46e5",radius:"Default",style:"Vega",base:"Neutral",font:"Inter",heading:"Medium"})}
  return <div className={`appearance-settings appearance-workspace ${compact?"compact":""}`}><header><div><span>PERSONALISATION</span><h1>Appearance</h1><p>Compact workspace styling. Changes apply instantly across your portal.</p></div><button onClick={reset}>Reset to defaults</button></header><section className="appearance-control-strip"><Control label="Theme"><div className="appearance-options">{["Dark","Light","System"].map(item=><button className={mode===item?"selected":""} onClick={()=>save({mode:item})} key={item}>{item==="Light"?"☀":item==="Dark"?"◐":"▣"} {item}</button>)}</div></Control><Control label="Radius"><AppearanceSelect value={radius} options={["Default","Small","Large","Sharp"]} onChange={value=>save({radius:value})}/></Control><Control label="Font"><AppearanceSelect value={font} options={["Inter","Geist","System","Roboto"]} onChange={value=>save({font:value})}/></Control><Control label="Heading"><AppearanceSelect value={heading} options={["Compact","Medium","Large"]} onChange={value=>save({heading:value})}/></Control></section><section><h2>Style</h2><div className="appearance-style-grid">{styles.map(item=><button className={style===item.name?"selected":""} onClick={()=>save({style:item.name})} key={item.name}><strong>{item.name}</strong><span>{item.copy}</span>{style===item.name&&<em>ACTIVE</em>}<i><b/><b/></i></button>)}</div></section><section><h2>Base colour</h2><div className="appearance-options">{Object.keys(bases).map(item=><button className={base===item?"selected":""} onClick={()=>save({base:item})} key={item}>{base===item&&"✓ "}{item}</button>)}</div></section><ColorRow title="Theme colour" value={color} onChange={value=>save({color:value})}/><ColorRow title="Chart colour" value={chartColor} onChange={value=>save({chartColor:value})}/><section className="appearance-preview"><h2>Preview</h2><div><aside><i/><i/><i/></aside><article><small>Active placements</small><strong>2,174</strong><span/><button>Primary action</button></article><article><small>Completion trend</small><svg viewBox="0 0 170 55"><polyline points="0,44 35,35 65,39 100,19 135,25 170,8"/></svg></article></div></section></div>
}

type AppearanceValue={mode:string;color:string;chartColor:string;radius:string;style:string;base:string;font:string;heading:string};
function applyAppearance(value:AppearanceValue){const root=document.documentElement;root.style.setProperty("--primary",value.color);root.style.setProperty("--purple",value.color);root.style.setProperty("--chart-color",value.chartColor);root.style.setProperty("--active-bg",`color-mix(in srgb, ${value.color} 11%, white)`);root.style.setProperty("--bg",bases[value.base as keyof typeof bases]||bases.Neutral);root.style.setProperty("--base-color",bases[value.base as keyof typeof bases]||bases.Neutral);root.style.setProperty("--portal-radius",value.radius==="Small"?"6px":value.radius==="Large"?"16px":value.radius==="Sharp"?"3px":"10px");root.style.setProperty("--portal-font",fonts[value.font as keyof typeof fonts]||fonts.Inter);root.style.setProperty("--heading-size",headingScale[value.heading as keyof typeof headingScale]||headingScale.Medium);root.style.setProperty("--density",value.style==="Nova"?"0.88":value.style==="Mira"?"0.78":value.style==="Maia"?"1.12":"1");root.dataset.portalTheme=value.mode.toLowerCase();root.dataset.portalStyle=value.style.toLowerCase()}

function Control({label,children}:{label:string;children:React.ReactNode}){return <div className="appearance-control"><span>{label}</span>{children}</div>}
function ColorRow({title,value,onChange}:{title:string;value:string;onChange:(value:string)=>void}){return <section><h2>{title}</h2><div className="appearance-colors">{colors.map(item=><button className={value===item.value?"selected":""} onClick={()=>onChange(item.value)} key={item.name}><i style={{background:item.value}}/>{item.name}{value===item.value&&<b>✓</b>}</button>)}</div></section>}
function AppearanceSelect({value,options,onChange}:{value:string;options:string[];onChange:(value:string)=>void}){const[open,setOpen]=useState(false);return <div className="appearance-select"><button onClick={()=>setOpen(!open)}>{value}<b>⌄</b></button>{open&&<div>{options.map(item=><button className={item===value?"selected":""} onClick={()=>{onChange(item);setOpen(false)}} key={item}>{item===value?"✓ ":""}{item}</button>)}</div>}</div>}
