"use client";

// Internship letter workflow.
// Coordinators edit the official letterhead/template, while students merge
// their school details into that template and download/print the result as PDF.
import {useEffect,useState} from "react";

type LetterTemplate={title:string;body:string;signatory:string;signatories:string[];letterhead:string;letterheadSubline:string;logo:string;contact:string};

const defaultBody="This is to introduce {{student_name}}, with student number {{student_id}}, a student of the Akenten Appiah-Menka University of Skills Training and Entrepreneurial Development (AAMUSTED), who is pursuing a four-year Bachelor of Education programme. The University requests that the student completes the Student Internship Programme at {{school_name}} from {{start_date}} to {{end_date}}. We would be most grateful if you could offer the student the opportunity to carry out the internship in your reputable institution. University supervisors and a monitoring team may visit during the internship period.";
const defaultSignatory="Ag. Head, Centre for Supported Teaching in Schools and Internship";
const defaultTemplate:LetterTemplate={title:"Introductory Letter for School Internship",body:defaultBody,signatory:defaultSignatory,signatories:[defaultSignatory],letterhead:"AKENTEN APPIAH-MENKA UNIVERSITY OF SKILLS TRAINING AND ENTREPRENEURIAL DEVELOPMENT",letterheadSubline:"Centre for Supported Teaching in Schools and Internship",logo:"/ustedlogo.jpeg",contact:"AAMUSTED · Kumasi Campus · cstsi@aamusted.edu.gh"};

function normalizeTemplate(template:Partial<LetterTemplate>):LetterTemplate{const signatories=template.signatories?.length?template.signatories:[template.signatory||defaultSignatory];return {...defaultTemplate,...template,signatory:signatories[0],signatories}}
function readTemplate():LetterTemplate{try{const saved=localStorage.getItem("sip-letter-template");return saved?normalizeTemplate(JSON.parse(saved)):defaultTemplate}catch{return defaultTemplate}}
function renderLetterHtml({template,body,school,address,date}:{template:LetterTemplate;body:string;school:string;address:string;date:string}){const signatories=(template.signatories?.length?template.signatories:[template.signatory]).map(item=>`<strong>${item}</strong>`).join("");return `<!doctype html><html><head><title>${template.title}</title><style>@page{size:A4;margin:18mm}*{box-sizing:border-box}body{margin:0;background:#e5e7eb;font-family:"Times New Roman",serif;color:#111}.page{width:210mm;min-height:297mm;margin:0 auto;background:#fff;padding:18mm 22mm;box-shadow:0 18px 45px rgba(15,23,42,.18);display:flex;flex-direction:column}header{display:flex;align-items:center;gap:18px;border-bottom:3px solid #8a1538;padding-bottom:12px;margin-bottom:18px}header img{width:58px;height:58px;object-fit:contain}header strong{display:block;color:#7f1d1d;font-size:15px;text-transform:uppercase;line-height:1.25}header span{display:block;color:#8a1538;font-size:11px;margin-top:3px}.date{text-align:right;font-size:11px;margin:10px 0 22px}address{font-style:normal;font-size:12px;line-height:1.65;margin-bottom:20px}p{font-size:12px;line-height:1.75;margin:0 0 15px;text-align:justify}h1{font-size:13px;text-transform:uppercase;text-decoration:underline;margin:18px 0 14px}.signature{margin-top:28px;font-size:12px}.signature strong{display:block;margin-bottom:4px}.signature span{display:block}.contact{border-top:3px solid #8a1538;margin-top:auto;padding-top:8px;text-align:center;font-size:10px;color:#4b5563}@media print{body{background:#fff}.page{box-shadow:none;margin:0;padding:0;width:auto;min-height:calc(297mm - 36mm)}}</style></head><body><main class="page"><header><img src="${template.logo}" alt=""><div><strong>${template.letterhead}</strong><span>${template.letterheadSubline}</span></div></header><div class="date">${date}</div><address>The Head of School<br>${school}<br>${address}</address><p>Dear Sir/Madam,</p><h1>${template.title}</h1><p>${body}</p><p>We remain thankful for your cooperation.</p><div class="signature">${signatories}<span>For: Director, CSTSI</span></div><div class="contact">${template.contact}</div></main><script>window.onload=function(){setTimeout(function(){window.print()},250)}</script></body></html>`}
function openPdfPrint(html:string,notify:(message:string)=>void){const popup=window.open("","_blank","width=900,height=1200");if(!popup){notify("Please allow pop-ups, then click Download template again to save as PDF.");return}popup.document.open();popup.document.write(html);popup.document.close()}

export function CoordinatorLetterSettings({notify}:{notify:(message:string)=>void}){
  const[template,setTemplate]=useState<LetterTemplate>(defaultTemplate);
  const[previewSchool,setPreviewSchool]=useState("Placement School");
  const[previewAddress,setPreviewAddress]=useState("School postal or physical address");
  useEffect(()=>setTemplate(readTemplate()),[]);
  function update(value:Partial<LetterTemplate>){setTemplate(current=>({...current,...value}))}
  function updateSignatory(index:number,value:string){setTemplate(current=>{const signatories=current.signatories.map((item,itemIndex)=>itemIndex===index?value:item);return {...current,signatories,signatory:signatories[0]||""}})}
  function addSignatory(){setTemplate(current=>({...current,signatories:[...current.signatories,"New signatory title"]}))}
  function removeSignatory(index:number){setTemplate(current=>{const signatories=current.signatories.filter((_,itemIndex)=>itemIndex!==index);const next=signatories.length?signatories:[defaultSignatory];return {...current,signatories:next,signatory:next[0]}})}
  function save(){localStorage.setItem("sip-letter-template",JSON.stringify({...template,updatedAt:new Date().toISOString()}));notify("Internship letter template saved.")}
  function downloadTemplate(){const body=template.body.replaceAll("{{student_name}}","{student_name}").replaceAll("{{student_id}}","{student_id}").replaceAll("{{school_name}}",previewSchool).replaceAll("{{start_date}}","{start_date}").replaceAll("{{end_date}}","{end_date}");openPdfPrint(renderLetterHtml({template,body,school:previewSchool,address:previewAddress,date:"22 July 2026"}),notify);notify("PDF preview opened. Choose Save as PDF in the print dialog.")}
  function chooseLogo(file?:File){if(!file)return;const reader=new FileReader();reader.onload=()=>update({logo:String(reader.result)});reader.readAsDataURL(file)}
  return <><section className="module-head"><div><span>OFFICIAL DOCUMENT</span><h1>Internship letter template</h1><p>Edit the letterhead, logo, school preview and official wording students will download as PDF.</p></div><div><button className="secondary" onClick={downloadTemplate}>⇩ Download template</button><button className="primary" onClick={save}>Save template</button></div></section><div className="letter-builder-grid"><section className="module-card letter-editor"><h2>Letterhead setup</h2><p>These details appear at the top and bottom of every internship letter.</p><div className="letter-logo-row"><img src={template.logo} alt="Letter logo preview"/><label><span>Logo</span><input type="file" accept="image/*" onChange={event=>chooseLogo(event.target.files?.[0])}/></label></div><label><span>Letterhead name</span><input value={template.letterhead} onChange={event=>update({letterhead:event.target.value})}/></label><label><span>Letterhead subheading</span><input value={template.letterheadSubline} onChange={event=>update({letterheadSubline:event.target.value})}/></label><label><span>Footer contact</span><input value={template.contact} onChange={event=>update({contact:event.target.value})}/></label><h2>Template content</h2><label><span>Letter title</span><input value={template.title} onChange={event=>update({title:event.target.value})}/></label><label><span>Preview school name</span><input value={previewSchool} onChange={event=>setPreviewSchool(event.target.value)}/></label><label><span>Preview school address / community</span><input value={previewAddress} onChange={event=>setPreviewAddress(event.target.value)}/></label><label><span>Letter body</span><textarea value={template.body} onChange={event=>update({body:event.target.value})}/></label><div className="letter-signatories"><div><h2>Signatories</h2><button type="button" className="secondary" onClick={addSignatory}>＋ Add signatory</button></div>{template.signatories.map((item,index)=><label key={index}><span>Signatory {index+1}</span><div className="letter-signatory-row"><input value={item} onChange={event=>updateSignatory(index,event.target.value)}/>{template.signatories.length>1&&<button type="button" onClick={()=>removeSignatory(index)}>Remove</button>}</div></label>)}</div><div className="letter-placeholders">{["{{student_name}}","{{student_id}}","{{school_name}}","{{start_date}}","{{end_date}}"].map(item=><code key={item}>{item}</code>)}</div></section><FormalLetter template={template} body={template.body} school={previewSchool} address={previewAddress} date="22 July 2026"/></div></>
}

export function StudentInternshipLetter({notify}:{notify:(message:string)=>void}){
  const[template,setTemplate]=useState<LetterTemplate>(defaultTemplate);
  const[school,setSchool]=useState("Asokwa M/A JHS");
  const[address,setAddress]=useState("Asokwa, Kumasi");
  const[start,setStart]=useState("2026-02-02");
  const[end,setEnd]=useState("2026-08-28");
  useEffect(()=>setTemplate(readTemplate()),[]);
  const letter=template.body.replaceAll("{{student_name}}","Kwame Mensah").replaceAll("{{student_id}}","5201040012").replaceAll("{{school_name}}",school).replaceAll("{{start_date}}",start).replaceAll("{{end_date}}",end);
  function download(){openPdfPrint(renderLetterHtml({template,body:letter,school,address,date:new Date().toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"})}),notify);notify("PDF preview opened. Choose Save as PDF in the print dialog.")}
  return <><section className="portal-page-head"><span>OFFICIAL DOCUMENT</span><h1>Internship letter</h1><p>Fill the school details, download the PDF, then submit it in person or by email.</p></section><div className="student-letter-layout"><section className="student-card letter-student-form"><h2>Complete letter details</h2><label><span>Placement school</span><input value={school} onChange={event=>setSchool(event.target.value)}/></label><label><span>School address / community</span><input value={address} onChange={event=>setAddress(event.target.value)}/></label><label><span>Internship start date</span><input type="date" value={start} onChange={event=>setStart(event.target.value)}/></label><label><span>Internship end date</span><input type="date" value={end} onChange={event=>setEnd(event.target.value)}/></label><button onClick={download}>Download completed PDF</button><small>Print and submit it to the school, or attach the saved PDF to an email.</small></section><FormalLetter template={template} body={letter} school={school} address={address} date={new Date().toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"})}/></div></>
}

function FormalLetter({template,body,school,address,date}:{template:LetterTemplate;body:string;school:string;address:string;date:string}){const signatories=template.signatories?.length?template.signatories:[template.signatory];return <article className="student-card printable-letter formal-letter"><header><img src={template.logo} alt="Letterhead logo"/><div><strong>{template.letterhead}</strong><span>{template.letterheadSubline}</span></div></header><time>{date}</time><address>The Head of School<br/>{school}<br/>{address}</address><p>Dear Sir/Madam,</p><h2>{template.title}</h2><p>{body}</p><p>We remain thankful for your cooperation.</p><footer>{signatories.map((item,index)=><strong key={`${item}-${index}`}>{item}</strong>)}<span>For: Director, CSTSI</span></footer><div className="letter-contact">{template.contact}</div></article>}
